name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    name: Build and Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - run: git diff origin/main...HEAD
      - run: pnpm turbo ls --affected

      - name: Build
        run: pnpm build:ci

      - name: Lint
        run: pnpm lint
