name: Docs Deploy to GitHub Pages

on:
  push:
    paths:
      - "apps/docs/**"
      - ".github/workflows/docs-deploy.yml"
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build storybook
        run: pnpm storybook:build

      - name: Copy web storybook
        run: cp -r ./apps/web/storybook-static ./apps/docs/static/storybook/web/

      - name: Copy ui storybook
        run: cp -r ./packages/ui/storybook-static ./apps/docs/static/storybook/ui/

      - name: Build website
        run: pnpm build --filter=docs

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./apps/docs/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
