name: VRT

on:
  pull_request:
    paths:
      - "apps/storybook/**"
      - "apps/web/**"
      - "packages/ui/**"
      - ".github/workflows/vrt.yml"
    branches: [main]
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  VRT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Setup "pnpm"
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Serve Storybook
        run: pnpm storybook:serve &

      - name: Run Screenshot
        run: pnpm --filter storybook run screenshot

      - name: Run reg-suit
        run: pnpm --filter storybook run reg-suit
